import Link from "next/link";
import { ArrowRight, ArrowUpRight, AudioLines, CheckCircle2, FileText, Mic2, Sparkles, Target } from "lucide-react";

export default function LandingPage() {
  return <div className="landing-page">
    <header className="landing-header"><Link className="brand" href="/"><span className="brand-mark"><AudioLines size={22}/></span><span>interview<span className="brand-light">ly</span><span className="brand-dot">.</span></span></Link><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#features">What you’ll get</a></nav><div className="landing-header-actions"><Link href="/login">Log in</Link><Link className="landing-nav-cta" href="/login?mode=signup">Get started <ArrowUpRight size={15}/></Link></div></header>
    <main><section className="landing-hero"><div className="landing-hero-copy"><span className="landing-kicker"><span/> FREE INTERVIEW PRACTICE</span><h1>The interview<br/>starts <em>before</em><br/>the interview.</h1><p>Stop guessing what to practice. Turn your resume and a job description into a personal interview session, answer out loud or in writing, and see where to improve. Free to get started.</p><div className="landing-hero-actions"><Link className="landing-primary" href="/login?mode=signup">Get started free <ArrowRight size={19}/></Link><a href="#how-it-works" className="landing-secondary">See how it works <span>↓</span></a></div><div className="landing-proof"><span><CheckCircle2 size={16}/> Behavioral + technical rounds</span><span><CheckCircle2 size={16}/> No payment required</span></div></div><div className="landing-visual" aria-label="Interview practice features"><div className="landing-orbit orbit-one"/><div className="landing-orbit orbit-two"/><div className="landing-visual-card"><div className="visual-card-top"><span className="visual-avatar"><AudioLines size={18}/></span><div><strong>Practice for your role</strong><small>BEHAVIORAL + TECHNICAL</small></div></div><div className="visual-progress"><span/></div><span className="visual-label">YOUR PRACTICE FLOW</span><h3>Prepare. Answer. Improve.</h3><div className="visual-wave"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="visual-card-bottom"><span><Mic2 size={17}/> Voice or text answers</span><span>Timer optional</span></div></div><div className="landing-floating-note"><Sparkles size={17}/><span><strong>Clearer every time.</strong><small>Learn from every answer.</small></span></div></div></section>
      <section className="landing-problem"><span className="section-index">THE PROBLEM</span><h2>Job interviews are hard to prepare for when you do not know what to practice.</h2><p>Generic question lists miss your experience and the role you want. Practicing alone gives you little feedback on what you said well or where your answer needs work.</p></section><section className="landing-trust"><span>BUILT AROUND YOUR NEXT OPPORTUNITY</span><div><strong>01</strong> Your experience <span>↗</span></div><div><strong>02</strong> Your target role <span>↗</span></div><div><strong>03</strong> Your growth <span>↗</span></div></section>
      <section id="how-it-works" className="landing-section"><div className="section-lead"><span className="section-index">THE PROCESS / 01</span><h2>From “what if?”<br/>to <em>“I’ve got this.”</em></h2><p>A simple practice loop that helps you prepare with more direction and less guesswork.</p></div><div className="landing-steps"><article><span>01 / SET THE SCENE</span><div className="landing-feature-icon"><FileText size={23}/></div><h3>Make it personal.</h3><p>Add the job description and your resume. Your practice questions reflect the role you’re aiming for.</p></article><article><span>02 / FIND YOUR VOICE</span><div className="landing-feature-icon"><Mic2 size={23}/></div><h3>Practice out loud.</h3><p>Move through behavioral and technical rounds. Speak or type, and turn the timer on or off.</p></article><article><span>03 / KEEP GROWING</span><div className="landing-feature-icon"><Target size={23}/></div><h3>Know your next step.</h3><p>Review strengths and gaps, retry answers, and find coding practice matched to your technical feedback.</p></article></div></section>
      <section id="features" className="landing-feature-band"><div><span className="section-index">THE BENEFITS</span><h2>More than a<br/><em>list of questions.</em></h2><p>Focus your practice on your target role, understand your strengths and gaps, and know what to work on next.</p><Link href="/login?mode=signup">Get started free <ArrowRight size={17}/></Link></div><div className="landing-feature-list"><div><span>01</span><strong>Questions shaped around your role</strong><Sparkles size={17}/></div><div><span>02</span><strong>Voice or text answers</strong><AudioLines size={17}/></div><div><span>03</span><strong>Feedback you can act on</strong><CheckCircle2 size={17}/></div><div><span>04</span><strong>Technical practice links</strong><ArrowUpRight size={17}/></div></div></section>
      <section className="landing-final"><span className="section-index">FREE TO START</span><h2>Walk into the next one<br/><em>feeling prepared.</em></h2><p>Create an account and start practicing without a payment method.</p><Link className="landing-primary" href="/login?mode=signup">Get started free <ArrowRight size={19}/></Link></section>
    </main><footer className="landing-footer"><span>© {new Date().getFullYear()} INTERVIEWLY</span><span>SHOW UP PREPARED. SHOW UP AS YOU.</span><Link href="/login">LOG IN ↗</Link></footer>
  </div>;
}
